Add Using Pinned Servers doc
wso2/docs-ei pull request #2842
Opened 2021-09-15 14:21 UTC by ruthryi

E -1190

2021-09-16 10:32 UTC, tdkmalan commented on en/micro-integrator/docs/use-cases/examples/proxy_service_examples/using-pinned-servers.md
> +The Synapse server name is specified in the system property `SynapseServerName` or through the `axis2.xml` parameter `SynapseConfig.ServerName`. If neither of these are set, the server hostname is us
"through the `axis2.xml` parameter `SynapseConfig.ServerName`. If neither of these are set" 
No longer use in the EI 7.0 version and later.

2021-09-16 10:34 UTC, tdkmalan requested changes
EI 7.0 after, the configuration is not done in axis2.xml. Please remove the below section. 
"through the `axis2.xml` parameter `SynapseConfig.ServerName`. If neither of these are set"

We can only keep the below section.   

The Synapse server name is specified in the system property `SynapseServerName. If this is not set then it defaults to localhost. You can give a name to a Synapse server instance by specifying the property `-DSynapseServerName=<ServerName>` when you execute the startup script `integrator.bat` or `integrator.sh`, or by editing `wrapper.conf` to do this where Synapse is started as a service.

2021-09-16 11:13 UTC, tdkmalan requested changes
startup script has been changed from "integrator.bat/.sh to
micro-integrator.bat and micro-integrator.sh

2021-09-16 12:41 UTC, tdkmalan approved these changes

2021-09-17 04:46 UTC, samgnaniah approved these changes

2021-09-17 04:46 UTC, merged